services:
  eos_ha:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/rockinglama/eos-ha:snapshot
    ports:
      - "8081:8081"
    volumes:
      - ./src/config.yaml:/app/config.yaml
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped